[package]
name = "borders"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "borders"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
image = { version = "0.25.5", default-features = false, features = ["jpeg", "png", "webp", "tiff", "bmp"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
